title: Larissa Huang
logo: images/headshot_resized.png
description: Technical Skills\:\ Python, SQL, Numpy, Pandas, sklearn, Machine Learning, Neural Networks, Statistical Analysis, Data Cleaning & Modeling, Big Data, Tensorflow, Tableau,
#show_downloads: true
theme: jekyll-theme-minimal
